### ISSUE TITLE
improve readme with actual command to configure luacheck linter

### ISSUE THREAD

**Issue by teto** [gbprod/none-ls-luacheck.nvim#2]
the `none_ls.builtins.diagnostics.luacheck.with({` was not working even when following this website's README.

seems like
```
sources = { 
   ...
     require("none-ls-luacheck.diagnostics.luacheck").with({
      extra_args = { '--ignore 21/_.*' }
     }),
}
```
does the deed

**Comment by gbprod** [comment]
I've improved the readme, thanks for your feedback ;)
